apiVersion: v1
kind: Service
metadata:
  name: ia
  labels:
    app: ia
spec:
  selector:
    app: ia
  ports:
    - port: 2000
      targetPort: 2000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ia
  labels:
    app:  ia
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  ia
  template:
    metadata:
      labels:
        app:  ia
    spec:
      containers:
      - name:  ia
        image: bastienbng/be-ia:1.0
        ports:
        - containerPort: 2000

---